/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PollsNewRouteImport } from './routes/polls.new'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as PollsPollIdAnalyticsRouteImport } from './routes/polls.$pollId.analytics'
import { Route as PSlugResultsRouteImport } from './routes/p.$slug_.results'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsNewRoute = PollsNewRouteImport.update({
  id: '/polls/new',
  path: '/polls/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsPollIdAnalyticsRoute = PollsPollIdAnalyticsRouteImport.update({
  id: '/polls/$pollId/analytics',
  path: '/polls/$pollId/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugResultsRoute = PSlugResultsRouteImport.update({
  id: '/p/$slug_/results',
  path: '/p/$slug/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/polls/new': typeof PollsNewRoute
  '/p/$slug/results': typeof PSlugResultsRoute
  '/polls/$pollId/analytics': typeof PollsPollIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/polls/new': typeof PollsNewRoute
  '/p/$slug/results': typeof PSlugResultsRoute
  '/polls/$pollId/analytics': typeof PollsPollIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/p/$slug': typeof PSlugRoute
  '/polls/new': typeof PollsNewRoute
  '/p/$slug_/results': typeof PSlugResultsRoute
  '/polls/$pollId/analytics': typeof PollsPollIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/p/$slug'
    | '/polls/new'
    | '/p/$slug/results'
    | '/polls/$pollId/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/p/$slug'
    | '/polls/new'
    | '/p/$slug/results'
    | '/polls/$pollId/analytics'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/register'
    | '/sso-callback'
    | '/p/$slug'
    | '/polls/new'
    | '/p/$slug_/results'
    | '/polls/$pollId/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  PSlugRoute: typeof PSlugRoute
  PollsNewRoute: typeof PollsNewRoute
  PSlugResultsRoute: typeof PSlugResultsRoute
  PollsPollIdAnalyticsRoute: typeof PollsPollIdAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/new': {
      id: '/polls/new'
      path: '/polls/new'
      fullPath: '/polls/new'
      preLoaderRoute: typeof PollsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$pollId/analytics': {
      id: '/polls/$pollId/analytics'
      path: '/polls/$pollId/analytics'
      fullPath: '/polls/$pollId/analytics'
      preLoaderRoute: typeof PollsPollIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug_/results': {
      id: '/p/$slug_/results'
      path: '/p/$slug/results'
      fullPath: '/p/$slug/results'
      preLoaderRoute: typeof PSlugResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  PSlugRoute: PSlugRoute,
  PollsNewRoute: PollsNewRoute,
  PSlugResultsRoute: PSlugResultsRoute,
  PollsPollIdAnalyticsRoute: PollsPollIdAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
